management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.minimarket: WARN
    org.springframework: WARN
